---@class InitContainer
---@field entityId string|nil
---@field entity unknown|nil
---@field interactableEntity unknown|nil
---@field items table<number, SInventoryItemType> Items in container
---@field holderItem SHolderItemType|nil Holder item of container
---@field maxSlot number
---@field maxWeight number
---@field isDestroyOnEmpty boolean|nil
---@field position Vector3|nil
---@field rotation Rotator|nil
---@field containerId string|nil
---@field timeExpired number|nil Unix timestamp when container expires

---@class ResponseGetContainer
---@field id string
---@field citizenId string
---@field items table<number,SInventoryItemType>
---@field maxSlot number
---@field maxWeight number
---@field isDestroyOnEmpty boolean
---@field position Vector3
---@field rotation Rotator
---@field displayModel string
---@field holderItem SHolderItemType|nil
---@field timeExpired number Unix timestamp when container expires

