---@class PlayerData
---@field source number|nil
---@field characterId number
---@field citizenId string
---@field license string
---@field name string
---@field money table
---@field characterInfo table
---@field job table
---@field gang table
---@field position Vector3
---@field metadata table
---@field netId number|nil

